### ISSUE TITLE
Exporter output # ERROR: Connection Error

### ISSUE THREAD

**Issue by Kybeer** [tillsteinbach/prosafe_exporter_python#58]
Hello,
I have a [Netgear GS308T Smart Switch](https://www.netgear.com/support/product/GS308T.aspx), and collecting its metrics with your Prometheus exporter looks like a very nice setup.

I have installed the latest version ([Container](https://hub.docker.com/r/tillsteinbach/prosafe_exporter_python)), but when I try to access the Prometheus Target - http://mycontainerhostip:9493/ - I get this error (I have redacted my IPs from below):

`# Exporter output # ERROR: Connection Error with host [switch-ip] `

My config.yml looks like this and I can access the switch on that IP + password:

```
global:
  retrieve_interval: 20.0
  retries: 10
  host: "0.0.0.0"
  port: 9493
switches:
  - hostname: "switch-ip"
    password: "my-password"
```

If I change the IP in config.yml to something else (i.e. something wrong), I get the same error. Do you know if there's any settings in the Netgear switch that need to allow such connection? It's a completely new, vanilla config, no VLANs, no ACLs etc. 

I know you have not listed the GS308T model as compatible in the README.
